### ISSUE TITLE
About Licensing

### ISSUE THREAD

**Issue by PINTO0309** [dannyso16/Gameboy-on-terminal#1]
Thanks for sharing your great repository!
What is the license of the resources in this repository? I'd like to cite it, but I'm a little confused.
https://github.com/PINTO0309/deep_running

**Comment by dannyso16** [comment]
@PINTO0309 Thanks for the comment. 
I've just set up an **MIT license** for this repository!  This is my first time setting up a license, so please let me know if there are any inconveniences.

By the way, I'm curious about "deep_running" and looking forward to it!!

**Comment by PINTO0309** [comment]
Thanks!! :smile_cat:
